name: ${project.artifactId}
version: ${project.version}
main: net.unlimi_server.custommotdmanager.CustomMotdManager
authors:  [fumyatan, NAFU_at]
website: https://github.com/fumyatan-Minecraft-Plugin-Archives

commands:
  custommotdmanager:
    description: To manipulate the Motd.
    aliases: [cmm]

Permissions:
  cmm.*:
    children:
      cmm.help: true
      cmm.getmotd: true
      cmm.addmotd: true
      cmm.remmotd: true
