name: ${project.artifactId}
version: ${project.version}
main: net.unlimi_server.custommotdmanager.CustomMotdManager
author: fumyatan
website: https://fumyatan.net

commands:
  cmm:
    description: To manipulate the Motd.
    usage: /<command>
  custommotdmanager:
    description: To manipulate the Motd.
    usage: /<command>

Permissions:
  CMM.*:
    description: To manipulate the Motd.
    children:
      CMM.help: true
      CMM.getmotd: true
      CMM.addmotd: true
      CMM.remmotd: true